import {
    Dimensions,
    StyleSheet,
  } from 'react-native';

const screenHeight = Dimensions.get('window').height;
const textBoxHeight = 0.1*screenHeight;
console.log(screenHeight);
export const styles = StyleSheet.create({
    Container:{
        padding: '10%',
        flex: 1,
        backgroundColor:'white',
    },
    subContainer:{
        paddingLeft: '10%',
        paddingRight: '10%',
        flex: 1,
        backgroundColor:'white',
    },
    subContainer2:{
        padding: '5%',
        flex: 1,
        backgroundColor:'white',
    },
    Wrapper: {
        flex: 1, 
        width: "100%", 
        alignItems:"center", 
        justifyContent:"center"
    },
    feedback: {
        fontSize: 14,
        color: 'red'
    },
    LogoView: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    insideView:{
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    textBox: {
        borderWidth: 1,
        height: 50,
        width: '100%',
        margin: 10,
        borderRadius: 10,
        borderColor:'#DDDDDD',
        padding: 5,
        paddingLeft: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    titleText: {
        color: '#E03621',
        fontSize: 24,
        textAlign: 'center',
        fontWeight: 'bold',
        fontFamily: 'Gotham',
    },
    midButton: {
        backgroundColor: '#F25846',
        borderRadius: 10,
        margin: 10,
        padding: 5,
        width: 138,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
    midText: {
        color: '#707070',
        fontFamily: 'Gotham',
        fontSize: 16,
    },
    radioText: {
        color: '#707070',
        fontFamily: 'Gotham',
        fontSize: 16,
        textAlign:'center'
    },
    headerText: {
        color: '#E03621',
        fontSize: 24,
        fontFamily: 'Gotham',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    headerTextLeft: {
        color: '#E03621',
        fontSize: 24,
        fontFamily: 'Gotham',
        fontWeight: 'bold',
        textAlign: 'left',
    },
    subheaderTextLeft: {
        color: '#E03621',
        fontSize: 18,
        fontFamily: 'Gotham',
        fontWeight: 'bold',
        textAlign: 'left',
    },
    helpText: {
        color: '#707070',
        fontSize: 10,
        fontFamily: 'Gotham',
    },  
    locText: {
        color: '#707070',
        fontSize: 18,
        fontFamily: 'Gotham-Medium',
        fontWeight: 'bold',
    },  
    subheadText: {
        color: '#707070',
        fontSize: 24,
        fontFamily: 'Gotham-Medium',
        fontWeight: 'bold',
    },  
    normalText: {
        color: '#707070',
        fontSize: 14,
        fontFamily: 'Gotham-Medium',
    },  
    inputTitle: {
        color: '#707070',
        fontSize: 16,
        fontFamily: 'Gotham',
        fontWeight: 'bold',
    },
    inputField: {
        width: '100%',
        flexDirection: 'row',
        borderBottomColor: '#CECECE',
        borderBottomWidth: 1,
        height: 50,
        alignItems:'center',
    },  
    regularButton: {
        backgroundColor: '#F25846',
        borderRadius: 10,
        margin: 10,
        padding: 5,
        width: 138,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    upTextBox: {
        borderWidth: 1,
        height: 50,
        margin: 10,
        borderRadius: 10,
        borderColor:'#DDDDDD',
        padding: 5,
        paddingLeft: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholder: {
        color: '#CECECE',
        fontSize: 18,
        fontFamily: 'Gotham-Medium',
    },
    placeholderActive: {
        color: '#707070',
        fontSize: 18,
        fontFamily: 'Gotham-Medium',
    },
    bannerHeader: {
        width: '100%',
        marginTop: 30,
        height: 70,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        backgroundColor: 'white',
        justifyContent: 'center'
    },
    tallHeader: {
        width: '100%',
        height: 150,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        backgroundColor: 'white',
        justifyContent: 'flex-start',
        padding: 10,
    },
    headerBox: {
        width: '100%',
        height: 80,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        backgroundColor: 'white',
        justifyContent: 'flex-end',
        paddingBottom: 10,
        paddingLeft: 10,
    },
    bannerList: {
        width: '100%',
        height: 80,
        marginBottom: 20,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 2.65,
        elevation: 3,
        backgroundColor: 'white',
        justifyContent: 'center',
        paddingLeft: 20,
        borderRadius: 10,
    },
    reqList: {
        width: '100%',
        height: 70,
        marginBottom: 10,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 2.65,
        elevation: 3,
        backgroundColor: 'white',
        justifyContent: 'center',
        paddingLeft: 20,
        borderRadius: 10,
    },
    subHead: {
        color: '#E03621',
        fontSize: 16,
        fontFamily: 'Gotham',
        textAlign: 'left',
    },
    headText: { 
        color: '#E03621',
        fontSize: 20,
        fontFamily: 'Gotham',
        textAlign: 'left',
        fontWeight: 'bold',
    },
    eventText: { 
        color: '#E03621',
        fontSize: 24,
        fontFamily: 'Gotham',
        textAlign: 'left',
        fontWeight: 'bold',
    },
    bigText: { 
        color: '#E03621',
        fontSize: 36,
        fontFamily: 'Gotham',
        textAlign: 'left',
        fontWeight: 'bold',
    },
    boxText: { 
        color: '#E03621',
        fontSize: 18,
        fontFamily: 'Gotham',
        textAlign: 'left',
    },
    boxText2: { 
        color: '#AA2D2D',
        fontSize: 14,
        fontFamily: 'Gotham',
        textAlign: 'left',
        fontWeight: 'bold'
    },

    carousel:{
        height: 150,
        width: '50%',
        margin: '3%',
        backgroundColor: 'white',
        borderRadius: 10,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        borderColor: '#CECECE',
        borderWidth: 1,
        padding: 8,
    },
    card:{
        height: 120,
        width: '50%',
        margin: '3%',
        backgroundColor: 'white',
        shadowColor: "#dddddd",
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        borderColor: '#CECECE',
        borderWidth: 1,
        borderRadius: 10,
        overflow: 'hidden',
    },
    btnFromText: {
        width: '100%',
        backgroundColor: '#F25846',
        color: 'white',
        paddingTop: 14,
        paddingBottom: 14,
        textAlign: "center",
        fontWeight: 'bold',
        fontSize: 18,
        borderRadius: 10,
    },
    activeTab: {
        backgroundColor: 'white',
        elevation: 6,
    },
    muteTab: {
        backgroundColor: 'white',
        elevation: 6,
    },
    whiteButton: {
        width: 120,
        height: 40,
        backgroundColor: 'white',
        color: '#F25846',
        borderColor: '#F25846',
        borderWidth: 1,
        paddingTop: 14,
        paddingBottom: 14,
        textAlign: "center",
        fontWeight: 'bold',
        fontSize: 18,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },  
    wbText: {
        color: '#F25846',
        fontSize: 14,
        fontWeight: 'bold',
        fontFamily: 'Gotham'
    }
})

