import {
    Dimensions,
    StyleSheet,
  } from 'react-native';

const screenHeight = Dimensions.get('window').height;
const textBoxHeight = 0.1*screenHeight;
console.log(screenHeight);
export const styles = StyleSheet.create({
    Container:{
        padding: '10%',
        flex: 1,
        backgroundColor:'white',
        fontFamily: 'Gotham',
    },
    LogoView: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    insideView:{
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
        width: '100%',
    },
    textBox: {
        borderWidth: 1,
        height: 50,
        width: '100%',
        margin: 10,
        borderRadius: 10,
        borderColor:'#DDDDDD',
        padding: 5,
        paddingLeft: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    titleText: {
        color: '#E03621',
        fontSize: 24,
        textAlign: 'center',
        fontWeight: 'bold',
        fontFamily: 'Gotham',
    },
    midButton: {
        backgroundColor: '#F25846',
        borderRadius: 10,
        margin: 10,
        padding: 5,
        width: 138,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
    midText: {
        color: '#707070',
        fontFamily: 'Gotham',
        fontSize: 16,
    },
    headerText: {
        color: '#E03621',
        fontSize: 24,
        fontFamily: 'Gotham',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    headerTextLeft: {
        color: '#E03621',
        fontSize: 24,
        fontFamily: 'Gotham',
        fontWeight: 'bold',
        textAlign: 'left',
    },
    inputTitle: {
        color: '#707070',
        fontSize: 16,
        fontFamily: 'Gotham',
        fontWeight: 'bold',
    },
    regularButton: {
        backgroundColor: '#F25846',
        borderRadius: 10,
        margin: 10,
        padding: 5,
        width: 138,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    upTextBox: {
        borderWidth: 1,
        height: 50,
        margin: 10,
        borderRadius: 10,
        borderColor:'#DDDDDD',
        padding: 5,
        paddingLeft: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bannerHeader: {
        width: '100%',
        marginTop: 30,
        height: 60,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        backgroundColor: 'white',
    },
    headerBox: {
        width: '100%',
        height: 80,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        backgroundColor: 'white',
        justifyContent: 'flex-end',
        paddingBottom: 15,
        paddingLeft: 40,
    },
    subHead: {
        color: '#E03621',
        fontSize: 14,
        fontFamily: 'Gotham',
        textAlign: 'left',
    },
    headText: { 
        color: '#E03621',
        fontSize: 18,
        fontFamily: 'Gotham',
        textAlign: 'left',
        fontWeight: 'bold',
    },
    boxText: { 
        color: '#E03621',
        fontSize: 18,
        fontFamily: 'Gotham',
        textAlign: 'left',
    },
    carousel:{
        height: 150,
        width: '50%',
        margin: '3%',
        backgroundColor: 'white',
        borderRadius: 10,
        shadowColor: "#dddddd",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.07,
        shadowRadius: 4.65,
        elevation: 6,
        borderColor: '#CECECE',
        borderWidth: 1,
        padding: 8,
    },
    btnFromText: {
        width: '100%',
        backgroundColor: '#F25846',
        color: 'white',
        paddingTop: 14,
        paddingBottom: 14,
        textAlign: "center",
        fontWeight: 'bold',
        fontSize: 18,
        borderRadius: 10,
    }
})

